---
- name: restart mysql
  service: name=mysqld state=restarted
  when: ansible_os_family == 'RedHat'

- name: restart mysql
  service: name=mysql state=restarted
  when: ansible_os_family == 'Debian'
